### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by coldn00dles** [arian-code/nptel_quantum_assignments#1]
are these all the possible questions from the course? Also how was the final exam

**Comment by arian-code** [comment]
It is from course. The exam is  online (multiple choice). All the best

**Comment by coldn00dles** [comment]
bro, I meant like how were the questions in the final exam. What was the overall difficulty? and if are there any samples available online.
And what about week 4 questions, were they all objective since I couldnt find them in your repo
